## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
url = 'https://raw.githubusercontent.com/kellsworth23/Deep_Learning_Challenge_New/main/Resources/charity_data.csv'
charity_df = pd.read_csv(url)
charity_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN', 'NAME', 'ORGANIZATION', 'USE_CASE', 'SPECIAL_CONSIDERATIONS'.
charity_df = charity_df.drop(columns = ['EIN', 'NAME', 'ORGANIZATION', 'USE_CASE', 'SPECIAL_CONSIDERATIONS'])

In [ ]:
# Determine the number of unique values in each column.
for x in charity_df.columns:
    print(x, len(charity_df[x].unique()))

APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
STATUS 2
INCOME_AMT 9
ASK_AMT 8747
IS_SUCCESSFUL 2

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
counts = charity_df['APPLICATION_TYPE'].value_counts()
counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(counts[counts < 700].index)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    charity_df['APPLICATION_TYPE'] = charity_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
charity_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
counts_for_binning = charity_df['CLASSIFICATION'].value_counts()

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = counts_for_binning[counts_for_binning > 1]
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list (counts_for_binning[counts_for_binning < 100].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    charity_df['CLASSIFICATION'] = charity_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
charity_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
charity_df = pd.get_dummies(charity_df,dtype=float)
charity_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,CLASSIFICATION_Other,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,108590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,6692,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,142590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Split our preprocessed data into our features and target arrays
y = charity_df['IS_SUCCESSFUL'].values
y

X = charity_df.drop('IS_SUCCESSFUL', axis=1).values
X
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=8
hidden_nodes_layer2=15
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_10 (Dense)            (None, 8)                 304

 dense_11 (Dense)            (None, 15)                135

 dense_12 (Dense)            (None, 1)                 16

=================================================================
Total params: 455
Trainable params: 455
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=120)

Epoch 1/120
684/684 [==============================] - 3s 3ms/step - loss: 0.6326 - accuracy: 0.6770 - val_loss: 0.5735 - val_accuracy: 0.7261
Epoch 2/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5711 - accuracy: 0.7170 - val_loss: 0.5575 - val_accuracy: 0.7367
Epoch 3/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5640 - accuracy: 0.7232 - val_loss: 0.5553 - val_accuracy: 0.7346
Epoch 4/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5621 - accuracy: 0.7245 - val_loss: 0.5558 - val_accuracy: 0.7344
Epoch 5/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7244 - val_loss: 0.5582 - val_accuracy: 0.7352
Epoch 6/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7248 - val_loss: 0.5567 - val_accuracy: 0.7344
Epoch 7/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7249 - val_loss: 0.5557 - val_accuracy: 0.7344
Epoch 8/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7251 - val_loss: 0.5568 - val_accuracy: 0.7321
Epoch 9/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7255 - val_loss: 0.5552 - val_accuracy: 0.7326
Epoch 10/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7259 - val_loss: 0.5557 - val_accuracy: 0.7344
Epoch 11/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7254 - val_loss: 0.5556 - val_accuracy: 0.7346
Epoch 12/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7250 - val_loss: 0.5548 - val_accuracy: 0.7341
Epoch 13/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5586 - accuracy: 0.7247 - val_loss: 0.5563 - val_accuracy: 0.7346
Epoch 14/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7259 - val_loss: 0.5561 - val_accuracy: 0.7331
Epoch 15/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7272 - val_loss: 0.5558 - val_accuracy: 0.7344
Epoch 16/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7259 - val_loss: 0.5558 - val_accuracy: 0.7346
Epoch 17/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7267 - val_loss: 0.5555 - val_accuracy: 0.7331
Epoch 18/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5580 - accuracy: 0.7259 - val_loss: 0.5571 - val_accuracy: 0.7352
Epoch 19/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5580 - accuracy: 0.7265 - val_loss: 0.5552 - val_accuracy: 0.7341
Epoch 20/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7267 - val_loss: 0.5566 - val_accuracy: 0.7344
Epoch 21/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5576 - accuracy: 0.7277 - val_loss: 0.5556 - val_accuracy: 0.7344
Epoch 22/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5574 - accuracy: 0.7266 - val_loss: 0.5561 - val_accuracy: 0.7328
Epoch 23/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5576 - accuracy: 0.7277 - val_loss: 0.5558 - val_accuracy: 0.7352
Epoch 24/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7273 - val_loss: 0.5555 - val_accuracy: 0.7359
Epoch 25/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7268 - val_loss: 0.5551 - val_accuracy: 0.7354
Epoch 26/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5574 - accuracy: 0.7271 - val_loss: 0.5551 - val_accuracy: 0.7359
Epoch 27/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7283 - val_loss: 0.5563 - val_accuracy: 0.7375
Epoch 28/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5571 - accuracy: 0.7273 - val_loss: 0.5563 - val_accuracy: 0.7344
Epoch 29/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5569 - accuracy: 0.7275 - val_loss: 0.5554 - val_accuracy: 0.7367
Epoch 30/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7276 - val_loss: 0.5554 - val_accuracy: 0.7344
Epoch 31/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7276 - val_loss: 0.5567 - val_accuracy: 0.7349
Epoch 32/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5569 - accuracy: 0.7278 - val_loss: 0.5590 - val_accuracy: 0.7341
Epoch 33/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7276 - val_loss: 0.5567 - val_accuracy: 0.7362
Epoch 34/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5568 - accuracy: 0.7277 - val_loss: 0.5571 - val_accuracy: 0.7344
Epoch 35/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5568 - accuracy: 0.7278 - val_loss: 0.5566 - val_accuracy: 0.7341
Epoch 36/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7271 - val_loss: 0.5573 - val_accuracy: 0.7344
Epoch 37/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7282 - val_loss: 0.5565 - val_accuracy: 0.7344
Epoch 38/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5562 - accuracy: 0.7272 - val_loss: 0.5577 - val_accuracy: 0.7357
Epoch 39/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7271 - val_loss: 0.5567 - val_accuracy: 0.7362
Epoch 40/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7277 - val_loss: 0.5587 - val_accuracy: 0.7352
Epoch 41/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5563 - accuracy: 0.7285 - val_loss: 0.5561 - val_accuracy: 0.7349
Epoch 42/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5563 - accuracy: 0.7274 - val_loss: 0.5557 - val_accuracy: 0.7352
Epoch 43/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5561 - accuracy: 0.7271 - val_loss: 0.5573 - val_accuracy: 0.7344
Epoch 44/120
684/684 [==============================] - 2s 2ms/step - loss: 0.5563 - accuracy: 0.7276 - val_loss: 0.5568 - val_accuracy: 0.7352
Epoch 45/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7278 - val_loss: 0.5559 - val_accuracy: 0.7367
Epoch 46/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5560 - accuracy: 0.7276 - val_loss: 0.5563 - val_accuracy: 0.7346
Epoch 47/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5560 - accuracy: 0.7284 - val_loss: 0.5560 - val_accuracy: 0.7354
Epoch 48/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7276 - val_loss: 0.5584 - val_accuracy: 0.7357
Epoch 49/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5562 - accuracy: 0.7279 - val_loss: 0.5562 - val_accuracy: 0.7344
Epoch 50/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7279 - val_loss: 0.5574 - val_accuracy: 0.7352
Epoch 51/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7287 - val_loss: 0.5562 - val_accuracy: 0.7354
Epoch 52/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5560 - accuracy: 0.7278 - val_loss: 0.5593 - val_accuracy: 0.7336
Epoch 53/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7288 - val_loss: 0.5571 - val_accuracy: 0.7334
Epoch 54/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7284 - val_loss: 0.5590 - val_accuracy: 0.7352
Epoch 55/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5557 - accuracy: 0.7276 - val_loss: 0.5565 - val_accuracy: 0.7336
Epoch 56/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7276 - val_loss: 0.5558 - val_accuracy: 0.7341
Epoch 57/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7283 - val_loss: 0.5577 - val_accuracy: 0.7344
Epoch 58/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5554 - accuracy: 0.7287 - val_loss: 0.5563 - val_accuracy: 0.7339
Epoch 59/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7278 - val_loss: 0.5572 - val_accuracy: 0.7349
Epoch 60/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7280 - val_loss: 0.5569 - val_accuracy: 0.7346
Epoch 61/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5560 - accuracy: 0.7279 - val_loss: 0.5575 - val_accuracy: 0.7372
Epoch 62/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7279 - val_loss: 0.5565 - val_accuracy: 0.7354
Epoch 63/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5557 - accuracy: 0.7280 - val_loss: 0.5561 - val_accuracy: 0.7354
Epoch 64/120
684/684 [==============================] - 3s 4ms/step - loss: 0.5555 - accuracy: 0.7285 - val_loss: 0.5569 - val_accuracy: 0.7365
Epoch 65/120
684/684 [==============================] - 2s 2ms/step - loss: 0.5557 - accuracy: 0.7271 - val_loss: 0.5572 - val_accuracy: 0.7359
Epoch 66/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7287 - val_loss: 0.5567 - val_accuracy: 0.7357
Epoch 67/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5551 - accuracy: 0.7281 - val_loss: 0.5568 - val_accuracy: 0.7349
Epoch 68/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5557 - accuracy: 0.7285 - val_loss: 0.5557 - val_accuracy: 0.7354
Epoch 69/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5552 - accuracy: 0.7286 - val_loss: 0.5583 - val_accuracy: 0.7352
Epoch 70/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5557 - accuracy: 0.7281 - val_loss: 0.5564 - val_accuracy: 0.7359
Epoch 71/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5552 - accuracy: 0.7283 - val_loss: 0.5582 - val_accuracy: 0.7341
Epoch 72/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5555 - accuracy: 0.7288 - val_loss: 0.5568 - val_accuracy: 0.7357
Epoch 73/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7286 - val_loss: 0.5561 - val_accuracy: 0.7362
Epoch 74/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5551 - accuracy: 0.7289 - val_loss: 0.5573 - val_accuracy: 0.7349
Epoch 75/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7285 - val_loss: 0.5589 - val_accuracy: 0.7349
Epoch 76/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5556 - accuracy: 0.7282 - val_loss: 0.5565 - val_accuracy: 0.7359
Epoch 77/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5554 - accuracy: 0.7281 - val_loss: 0.5561 - val_accuracy: 0.7341
Epoch 78/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7281 - val_loss: 0.5577 - val_accuracy: 0.7334
Epoch 79/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5555 - accuracy: 0.7290 - val_loss: 0.5569 - val_accuracy: 0.7346
Epoch 80/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7279 - val_loss: 0.5586 - val_accuracy: 0.7362
Epoch 81/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7287 - val_loss: 0.5569 - val_accuracy: 0.7352
Epoch 82/120
684/684 [==============================] - 2s 2ms/step - loss: 0.5554 - accuracy: 0.7285 - val_loss: 0.5564 - val_accuracy: 0.7359
Epoch 83/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5555 - accuracy: 0.7281 - val_loss: 0.5568 - val_accuracy: 0.7359
Epoch 84/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5552 - accuracy: 0.7286 - val_loss: 0.5576 - val_accuracy: 0.7357
Epoch 85/120
684/684 [==============================] - 2s 2ms/step - loss: 0.5555 - accuracy: 0.7290 - val_loss: 0.5569 - val_accuracy: 0.7352
Epoch 86/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5555 - accuracy: 0.7281 - val_loss: 0.5568 - val_accuracy: 0.7349
Epoch 87/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5551 - accuracy: 0.7283 - val_loss: 0.5565 - val_accuracy: 0.7359
Epoch 88/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7287 - val_loss: 0.5566 - val_accuracy: 0.7354
Epoch 89/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5554 - accuracy: 0.7281 - val_loss: 0.5567 - val_accuracy: 0.7354
Epoch 90/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5551 - accuracy: 0.7286 - val_loss: 0.5573 - val_accuracy: 0.7357
Epoch 91/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5551 - accuracy: 0.7284 - val_loss: 0.5555 - val_accuracy: 0.7349
Epoch 92/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5552 - accuracy: 0.7284 - val_loss: 0.5577 - val_accuracy: 0.7362
Epoch 93/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5552 - accuracy: 0.7283 - val_loss: 0.5569 - val_accuracy: 0.7359
Epoch 94/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5551 - accuracy: 0.7282 - val_loss: 0.5564 - val_accuracy: 0.7354
Epoch 95/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7284 - val_loss: 0.5566 - val_accuracy: 0.7354
Epoch 96/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5552 - accuracy: 0.7279 - val_loss: 0.5565 - val_accuracy: 0.7344
Epoch 97/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5551 - accuracy: 0.7285 - val_loss: 0.5570 - val_accuracy: 0.7344
Epoch 98/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5553 - accuracy: 0.7288 - val_loss: 0.5564 - val_accuracy: 0.7349
Epoch 99/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7289 - val_loss: 0.5577 - val_accuracy: 0.7344
Epoch 100/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5552 - accuracy: 0.7292 - val_loss: 0.5580 - val_accuracy: 0.7349
Epoch 101/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5550 - accuracy: 0.7279 - val_loss: 0.5577 - val_accuracy: 0.7344
Epoch 102/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7280 - val_loss: 0.5570 - val_accuracy: 0.7359
Epoch 103/120
684/684 [==============================] - 2s 4ms/step - loss: 0.5551 - accuracy: 0.7284 - val_loss: 0.5561 - val_accuracy: 0.7341
Epoch 104/120
684/684 [==============================] - 3s 4ms/step - loss: 0.5551 - accuracy: 0.7274 - val_loss: 0.5573 - val_accuracy: 0.7359
Epoch 105/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5552 - accuracy: 0.7282 - val_loss: 0.5567 - val_accuracy: 0.7346
Epoch 106/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5551 - accuracy: 0.7286 - val_loss: 0.5587 - val_accuracy: 0.7341
Epoch 107/120
684/684 [==============================] - 2s 3ms/step - loss: 0.5551 - accuracy: 0.7281 - val_loss: 0.5568 - val_accuracy: 0.7359
Epoch 108/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5550 - accuracy: 0.7290 - val_loss: 0.5567 - val_accuracy: 0.7367
Epoch 109/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5547 - accuracy: 0.7284 - val_loss: 0.5588 - val_accuracy: 0.7362
Epoch 110/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7284 - val_loss: 0.5568 - val_accuracy: 0.7359
Epoch 111/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5547 - accuracy: 0.7282 - val_loss: 0.5574 - val_accuracy: 0.7344
Epoch 112/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5551 - accuracy: 0.7279 - val_loss: 0.5561 - val_accuracy: 0.7349
Epoch 113/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5547 - accuracy: 0.7282 - val_loss: 0.5576 - val_accuracy: 0.7346
Epoch 114/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5550 - accuracy: 0.7281 - val_loss: 0.5564 - val_accuracy: 0.7341
Epoch 115/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5547 - accuracy: 0.7283 - val_loss: 0.5577 - val_accuracy: 0.7349
Epoch 116/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5548 - accuracy: 0.7288 - val_loss: 0.5568 - val_accuracy: 0.7346
Epoch 117/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5549 - accuracy: 0.7287 - val_loss: 0.5568 - val_accuracy: 0.7359
Epoch 118/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5548 - accuracy: 0.7287 - val_loss: 0.5570 - val_accuracy: 0.7349
Epoch 119/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5550 - accuracy: 0.7286 - val_loss: 0.5574 - val_accuracy: 0.7359
Epoch 120/120
684/684 [==============================] - 1s 2ms/step - loss: 0.5551 - accuracy: 0.7283 - val_loss: 0.5579 - val_accuracy: 0.7362

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5621 - accuracy: 0.7277 - 329ms/epoch - 1ms/step
Loss: 0.5620572566986084, Accuracy: 0.7276967763900757

In [ ]:
# Export our model to HDF5 file
from google.colab import files

nn.save('AlphabetSoupCharity_Optimization.h5')
files.download('AlphabetSoupCharity_Optimization.h5')